ALTER TABLE rounds
  ADD COLUMN IF NOT EXISTS sync_issue BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE players
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

ALTER TABLE clubs
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

-- Safe to run even if EPIC-0003 shipped first
ALTER TABLE teams
  ADD COLUMN IF NOT EXISTS team_size SMALLINT NOT NULL DEFAULT 4
    CHECK (team_size BETWEEN 2 AND 5);

ALTER TABLE team_members
  ADD COLUMN IF NOT EXISTS is_captain BOOLEAN NOT NULL DEFAULT false;
